version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      # - pgdata:/var/lib/postgresql/data
      - ./db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"
    # networks:
    #   - back-network
    restart: always

  py:
    build: ./py



# networks:
#   back-network:
#     driver: bridge

# volumes:
#   pgdata:
#     driver: local
